services:
  db:
    image: postgres:16
    container_name: lockboxassign_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: lockboxassign
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
